version: '3.5'

services:
  postgres-db:
    image: postgres:14
    container_name: neo_db_pg
    volumes:
      - neo_pg:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: neo_db_pg
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    ports:
      - "5432:5432"

  pgadmin4:
    image: dpage/pgadmin4:7.4
    container_name: pg_admin4
    environment:
      PGADMIN_DEFAULT_EMAIL: alekskarrrl@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "8082:80"

volumes:
  neo_pg:
    name: neo_pg

networks:
  default:
    name: neo-project-net


